### ISSUE TITLE
Bogaudio LPG and LLPG response appears to be broken on MM

### ISSUE THREAD

**Issue by voltagecontrolled** [4ms/metamodule-plugin-examples#3]
I've tried both creating a patch in VCV and locally on the module itself, and whenever I incorporate either of these two modules, they appear not to work properly on the Meta Module.

Specifically, when "striking" them with a trigger or gate, they do nothing until the lowest Response setting, and at probably the bottom 2-3% of the parameter just emit clicks. 

I'll attach both the VCV patch and the MM patch so you can see the behavior. **_Mind your speakers when playing this patch on MM._**

Notice that when you play the patch on the module, you'll hear no audio unless you turn up the Cutoff or VCA amount. Setting Response to its lowest setting will produce clicks, but anything above roughly 2-3% just generates a constant tone or nothing.

[LPGExample.yml.zip](https://github.com/user-attachments/files/16828989/LPGExample.yml.zip)
[LLPG_Issue.vcv.zip](https://github.com/user-attachments/files/16828996/LLPG_Issue.vcv.zip)

**Comment by danngreen** [comment]
We can confirm this.
We're going through all the Bogaudio modules right now and testing them more in-depth.

**Comment by danngreen** [comment]
This should be fixed in the upcoming v1.0.16 plugin release
