### ISSUE TITLE
Audible Instruments Resonator knob allocation display error

### ISSUE THREAD

**Issue by UMCorps** [4ms/metamodule-plugin-examples#5]
There is a mismatch between the knob allocation and how it is displayed on graphics for the AI Resonator.

In the attached patch Position is allocated to encoder E. That allocation shows up correctly in the knob view and works when the knob is turned. But back in the graphic for the Resonator, turning knob E appears to turn knob C allocated to Brighness.

It's just a display issue. Knob C still controls Brightness and E controls Position. It just looks confusing 

[Ringsextexciter.yml.zip](https://github.com/user-attachments/files/16868936/Ringsextexciter.yml.zip)

**Comment by danngreen** [comment]
Thanks, good find. Brightness and Position have their XY positions swapped. This technically isn't a plugin, so I'm going to close this here and open it here: https://github.com/4ms/metamodule/issues/362

**Comment by danngreen** [comment]
BTW, this is fixed in v1.1.1
