### ISSUE TITLE
Fundamental : quantizer - offset

### ISSUE THREAD

**Issue by TheTechnobear** [4ms/metamodule-plugin-examples#7]
in VCV offset is bipolar - +/- 12 semis (aka +/-1 1.f ) , it defaults to 0v

in MM offset is unipolar 0..1f , and default to 50% - so its default to +6 semi.
it needs default changing and ranging expanding.

I did not test, with vcv to see if the offset is being applied correctly.

note: also its labelled as 'preoffset' - this is confusing for user.

(I understand why... as its added to pitch before quantisation - however it should just be the same as vcv)

**Comment by danngreen** [comment]
Ok, thanks. I just pushed a fix for that, it'll be in the next plugin release
